name: smart_attendance
description: Smart Attendance System with Face Recognition
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ Tambahkan logger DI SINI (sejajar dengan flutter, bukan di dalamnya)
  logger: ^2.0.2+1

  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_spinkit: ^5.2.0

  # State Management
  provider: ^6.1.1

  # Network & API
  dio: ^5.4.0
  http: ^1.1.2

  # Local Storage (Sanctum Token)
  shared_preferences: ^2.2.2

  # Camera & Face Recognition
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.10.0
  image_picker: ^1.0.7
  image: ^4.1.7

  # Export (PDF & Excel)
  pdf: ^3.10.8
  path_provider: ^2.1.2
  open_filex: ^4.3.4

  geolocator: ^13.0.2          # ✅ TAMBAH INI
  
  # Permissions
  permission_handler: ^11.2.0

  # Charts
  fl_chart: ^0.66.0

  # Date Formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
  - assets/images/download.png
